name: CI e CD do TomEye

on:
  push:
    branches:
      - main

jobs:

  test:
    name: Testes automatizados - CI
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Executar testes
        run: node --test tests/api.test.js


  package:
    name: Empacotar projeto - CD
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Criar arquivo ZIP
        run: zip -r TomEye-TCC-2026.zip . -x ".git/*"

      - name: Validar arquivo ZIP
        run: unzip -t TomEye-TCC-2026.zip

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: TomEye-TCC-2026
          path: TomEye-TCC-2026.zip
